# Generated by Django 3.2.3 on 2021-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='date_watered',
            field=models.DateField(default=None),
        ),
    ]
