# Generated by Django 3.2.3 on 2021-05-17 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_plant_date_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_watered',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 15, 13, 55, 40099)),
        ),
    ]
