# Generated by Django 3.2.3 on 2021-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fertilizer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='date',
            field=models.DateField(verbose_name='fertilize date'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='type',
            field=models.CharField(choices=[('A', 'Soil Conditioner'), ('B', 'Stage 1 - Nitro'), ('C', 'Stage 2 - Grow'), ('D', 'Stage 3 - Bloom')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.Pot'),
        ),
    ]
